apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.11.1
      chart: cert-manager
  syncPolicy:
    automated:
      prune: true
