apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

commonLabels:
  app.kubernetes.io/name: cert-manager
  app.kubernetes.io/managed-by: argocd-argoproj.io

commonAnnotations:
  managed-by: argocd.argoproj.io

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.11.1
    namespace: cert-manager
    releaseName: cert-manager
    includeCRDs: true
    valuesInline:
      installCRDs: true
      #      prometheus:
      #        enabled: true
      #        servicemonitor:
      #          enabled: true
      #          prometheusInstance: forge-monitoring
      #      webhook:
      #        extraArgs:
      #          - "--feature-gates=AdditionalCertificateOutputFormats=true"
      #      csiDriver:
      #        install: true
      #      featureGates: "AdditionalCertificateOutputFormats=true"
      #      extraArgs:
      #        - "--controllers=*,-certificaterequests-approver"
    valuesMerge: override


