apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cert-mgr.yaml

commonLabels:
  app.kubernetes.io/name: cert-manager
  app.kubernetes.io/managed-by: argocd-argoproj.io

commonAnnotations:
  managed-by: argocd.argoproj.io

generatorOptions:
  disableNameSuffixHash: true


